### ISSUE TITLE
YouTube API key

### ISSUE THREAD

**Issue by sandervankasteel** [IceTimux/soundparadise#1]
Maybe you should remove your YouTube API key from this repo ?

Source: https://github.com/IceTimux/soundparadise/blob/master/config/youtube.php

**Comment by rjrhaverkamp** [comment]
Maybe store your API key in an environment variable? [php getenv](http://php.net/manual/en/function.getenv.php)

**Comment by IceTimux** [comment]
Whooooops dont know how I missed this

**Comment by IceTimux** [comment]
fixed, will completely remove it later, not really important
